### ISSUE TITLE
Touch Not Working

### ISSUE THREAD

**Issue by diginfo** [loboris/ESP32_TFT_library#15]
Hi;

Device = Lolin 32
Display = ILI9341  + XPT2046/ADS7846 (EastRising ER-TFTM028-4)

I am able to display all of the demos, and have checked the connections several times to be sure they are correct, I am using the default settings, and during the dispFont() demo, touching the screen has no effect.

```
#Set correct configuration
tft.init(tft.ILI9341, width=240, height=320, miso=19,mosi=23,clk=18,cs=5,dc=26,tcs=27,hastouch=True, bgr=True)

maxx = 240
maxy = 320
miny = 12
touch = False
```

If I change touch=True the demo won't start with the following error:

```
>>> import test.tft as tft
>>> tft.dispFont()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test/tft.py", line 107, in dispFont
  File "test/tft.py", line 43, in touched
OSError: Touch not configured
>>>
```

The same display and touch works on the raspberry PI - any idea what may be wrong ?

**Comment by diginfo** [comment]
Strange, I've not change anything but powered it up again today, ran dispFont() touched the screen and it works !

So I am closing this.
